package main.ui;

public class ChessUI extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel1
     */
    public ChessUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(750, 750));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 750, Short.MAX_VALUE)
        );

        add(jPanel1);
        jPanel1.setBounds(0, 100, 750, 750);

        jTextPane1.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jTextPane1.setText("Clicking a piece will show the possible moves in yellow squares. After clicking the piece, you can click it again to go back to choosing which piece to move again. A red square on a piece means that the piece in red is checking the opposite team's king.");
        jTextPane1.setMaximumSize(new java.awt.Dimension(750, 100));
        jTextPane1.setMinimumSize(new java.awt.Dimension(750, 100));
        jScrollPane1.setViewportView(jTextPane1);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 750, 100);
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration
}

